### PR TITLE
[BSE-4351] Generate lock with windows mpi

### PR DESCRIPTION
**Pull request by mbojanowski**
## Changes included in this PR
I was albe to build lock only after upgrading mpi4py: otherwise I have this error

```
Could not solve for environment specs
The following packages are incompatible
\u251c\u2500 impi-devel 2021.13.1**  is installable and it requires
\u2502  \u2514\u2500 impi_rt [2021.13.1 h57928b3_766|2021.13.1 h57928b3_767], which requires
\u2502     \u2514\u2500 mpi 1.0 impi, which can be installed;
\u251c\u2500 mpi4py ~=3.1  is installable with the potential options
\u2502  \u251c\u2500 mpi4py [3.1.0|3.1.1|...|3.1.6] would require
\u2502  \u2502  \u2514\u2500 msmpi [ |>=10.1,<10.2.0a0 ], which requires
\u2502  \u2502     \u2514\u2500 mpi 1.0 msmpi, which conflicts with any installable versions previously reported;
\u2502  \u251c\u2500 mpi4py [3.1.5|3.1.6] would require
\u2502  \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which can be installed;
\u2502  \u251c\u2500 mpi4py [3.1.5|3.1.6] would require
\u2502  \u2502  \u2514\u2500 python_abi 3.11.* *_cp311, which can be installed;
\u2502  \u251c\u2500 mpi4py 3.1.5 would require
\u2502  \u2502  \u2514\u2500 impi_rt >=2021.11.0,<2021.11.1.0a0 , which conflicts with any installable versions previously reported;
\u2502  \u251c\u2500 mpi4py [3.1.5|3.1.6] would require
\u2502  \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which can be installed;
\u2502  \u251c\u2500 mpi4py [3.1.5|3.1.6] would require
\u2502  \u2502  \u2514\u2500 pypy3.9 >=7.3.15 , which can be installed;
\u2502  \u251c\u2500 mpi4py [3.1.5|3.1.6] would require
\u2502  \u2502  \u2514\u2500 python_abi 3.9.* *_cp39, which can be installed;
\u2502  \u2514\u2500 mpi4py 3.1.6 would require
\u2502     \u2514\u2500 impi_rt >=2021.12.0,<2021.12.1.0a0 , which conflicts with any installable versions previously reported;
\u2514\u2500 python 3.12**  is not installable because there are no viable options
   \u251c\u2500 python [3.12.0|3.12.1|...|3.12.8] would require
   \u2502  \u2514\u2500 python_abi 3.12.* *_cp312, which conflicts with any installable versions previously reported;
   \u2514\u2500 python 3.12.0rc3 would require
      \u2514\u2500 _python_rc, which does not exist (perhaps a missing channel).
```

Changes:
- added windows 64 plaftorm
- disable hdf5,mpich for windows build
- added impi-devel for windows build
- disabled mpi4py-3.1.x  for windows
- enabled mpi4py-4.0.1 for windows

## Checklist
- [ ] Pipelines passed before requesting review. To run CI you must include `[run CI]` in your commit message.
- [ ] I am familiar with the [Contributing Guide](https://github.com/bodo-ai/Bodo/blob/main/CONTRIBUTING.md) 
- [ ] I have installed + ran pre-commit hooks.

### CODE REVIEW

**Comment by mbojanowski** [comment]
Also I was able to use mpi4py with ~3.1, but only with older version of impi

```
  - hdf5 >=1.14.3,<1.14.4.0a0=mpi_mpich_*  #[not win]
  - mpich <4.2=h*  #[not win]
  - mpi4py ~= 3.1
  - impi-devel=2021.12.0  #[win64]
```

**Review by ehsantn — APPROVED** [review]
Looks good to me. Do we need to use conda-lock? Can Pixi work?

**Comment by mbojanowski** [comment]
> Looks good to me. Do we need to use conda-lock? Can Pixi work?

I just check dependencies in conda-lock at,  thats all I will try build pixi as other things are build with that. 

so which option we should use:
1) upgrade mpi4py with impi-devel=2021.13.1?
2) use impi-devel=2021.12.0?

I get impresion that upgrading mpi4py  to 4.x can be a problem.

**Comment by ehsantn** [comment]
It can be a problem for platform which is Linux but upgrading for Windows the way you have it should be fine. @srilman ?

**Comment by srilman** [comment]
@ehsantn @mbojanowski We talked about it during oncall, and yes it is fine as is but lets check if there are any breaking changes between `mpi4py` 3 and 4 that we need to keep track of. I ask because we're not testing Windows anywhere. Can we discuss further during standup?

**Comment by ehsantn** [comment]
Sure, let's chat during standup.

**Pull request closed without merging**
