### PR TITLE
[BSE-4374] Patch numba for object mode globals in spawn mode

### PR DESCRIPTION
**Pull request by scott-routledge2**
## Changes included in this PR

Attach function global dictionary to `global_dict` of function descriptor when running in object mode with block. Otherwise keep the old behavior which avoids setting global_dict for caching.

## Testing strategy

Ran CI and Nightly

## Checklist
- [ ] Pipelines passed before requesting review. To run CI you must include `[run CI]` in your commit message.
- [x] I am familiar with the [Contributing Guide](https://github.com/bodo-ai/Bodo/blob/main/CONTRIBUTING.md) 
- [x] I have installed + ran pre-commit hooks.

### CODE REVIEW

**Comment by scott-routledge2** [comment]
Nightly spawn mode timed out and didn't show any logs so I am rerunning it to get the logs. Other failures are unrelated.

**Comment by scott-routledge2** [comment]
Looks like one of the caching tests is seg faulting: https://dev.azure.com/bodo-inc/Bodo/_build/results?buildId=25361&view=logs&j=85fc0caa-700e-53da-bd71-fcebe6eb44fc&t=da42c692-327a-56ca-753b-dab0fc9731a2&l=1781

**Review by ehsantn — APPROVED** [review]
Thanks @scott-routledge2 .

**Review by IsaacWarren — APPROVED** [review]
Thanks Scott

**Pull request merged**
