### PR TITLE
Add LLM query example with Ollama

### PR DESCRIPTION
**Pull request by ehsantn**
## Changes included in this PR

Adds an example that demonstrates preprocessing data and querying an LLM using Bodo (with Ollama).

## Testing strategy

Tested it locally.

## User facing changes

A new example.

## Checklist
- [N/A] Pipelines passed before requesting review. To run CI you must include `[run CI]` in your commit message.
- [x] I am familiar with the [Contributing Guide](https://github.com/bodo-ai/Bodo/blob/main/CONTRIBUTING.md) 
- [x] I have installed + ran pre-commit hooks.

### CODE REVIEW

**Review by scott-routledge2 — APPROVED** [review]
LGTM, is there a larger dataset of queries we could use to show performance benefits over python?

**Comment by ehsantn** [comment]
Running LLMs locally without GPUs is very slow so larger data would make it not usable.

**Comment by marquisdepolis** [comment]
Ollama is meant for local runs, smaller scale w/o GPUs. Next we can use
OpenAI compatible APIs, via https://github.com/andrewyng/aisuite or
LiteLLM, at larger scale, and see how that helps.

**Review by marquisdepolis — APPROVED** [review]
I'd edit to model="llama3", or even make that an outside variable, to keep it cleaner. And add a comment next to raw_prompts*10 that this just runs the examples 10x times.

**Comment by ehsantn** [comment]
Done.

**Pull request merged**
