### PR TITLE
Avoid importing BodoSQL unnecessarily

### PR DESCRIPTION
**Pull request by ehsantn**
## Changes included in this PR

This avoids importing BodoSQL unnecessarily which can cause issues issues if BodoSQL is not installed properly (e.g. Java issues). Also reduces compilation time a bit.

## Testing strategy

Tested it manually to make sure bodosql isn't imported.

## Checklist
- [x] Pipelines passed before requesting review. To run CI you must include `[run CI]` in your commit message.
- [x] I am familiar with the [Contributing Guide](https://github.com/bodo-ai/Bodo/blob/main/CONTRIBUTING.md) 
- [x] I have installed + ran pre-commit hooks.

### CODE REVIEW

**Review by IsaacWarren — APPROVED** [review]
Thanks Ehsan, can we add a simple test that compiles a simple function and asserts bodosql isn't imported just to make sure this doesn't regress

**Comment by ehsantn** [comment]
My concern is that our testing infrastructure itself may import BodoSQL and we don't have control over it.

**Comment by IsaacWarren** [comment]
> My concern is that our testing infrastructure itself may import BodoSQL and we don't have control over it.

We could do it in a subprocess, this seems important and like it could easily be readded by mistake

**Review by scott-routledge2 — APPROVED** [review]
Thanks @ehsantn

**Comment by ehsantn** [comment]
> > My concern is that our testing infrastructure itself may import BodoSQL and we don't have control over it.
> 
> We could do it in a subprocess, this seems important and like it could easily be re-added by mistake

Looks like only one test was importing BodoSQL so I just updated it.

**Pull request merged**
